"""empty message

Revision ID: 04fa8b9610f0
Revises: 874e3ee1d47c
Create Date: 2020-02-22 14:26:30.011914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04fa8b9610f0'
down_revision = '874e3ee1d47c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.alter_column('users', 'google_token',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'google_token',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###
