"""empty message

Revision ID: 0ec1f3362d72
Revises: 2c3036fdb5ee
Create Date: 2020-03-30 21:01:06.140732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ec1f3362d72'
down_revision = '2c3036fdb5ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['forms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.add_column('form_results', sa.Column('token_id', sa.Integer(), nullable=False))
    op.create_unique_constraint('unique_user_token', 'form_results', ['user_id', 'token_id'])
    op.drop_constraint('unique_user_form', 'form_results', type_='unique')
    op.drop_constraint('form_results_form_id_fkey', 'form_results', type_='foreignkey')
    op.create_foreign_key(None, 'form_results', 'tokens', ['token_id'], ['id'])
    op.drop_column('form_results', 'form_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_results', sa.Column('form_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'form_results', type_='foreignkey')
    op.create_foreign_key('form_results_form_id_fkey', 'form_results', 'forms', ['form_id'], ['id'])
    op.create_unique_constraint('unique_user_form', 'form_results', ['user_id', 'form_id'])
    op.drop_constraint('unique_user_token', 'form_results', type_='unique')
    op.drop_column('form_results', 'token_id')
    op.drop_table('tokens')
    # ### end Alembic commands ###
