"""empty message

Revision ID: 27b26ea9d40e
Revises: a4ff0ba9384a
Create Date: 2020-02-18 18:17:10.081374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27b26ea9d40e'
down_revision = 'a4ff0ba9384a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forms', sa.Column('is_published', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forms', 'is_published')
    # ### end Alembic commands ###
