"""empty message

Revision ID: 2c3036fdb5ee
Revises: cb1f0d8fcc8d
Create Date: 2020-03-17 23:56:38.407758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c3036fdb5ee'
down_revision = 'cb1f0d8fcc8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shared_fields', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'shared_fields', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shared_fields', type_='foreignkey')
    op.drop_column('shared_fields', 'owner_id')
    # ### end Alembic commands ###
