"""empty message

Revision ID: 6d75e485a6af
Revises: 27b26ea9d40e
Create Date: 2020-02-20 17:34:36.070675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d75e485a6af'
down_revision = '27b26ea9d40e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ranges', sa.Column('max_value', sa.Integer(), nullable=True))
    op.add_column('ranges', sa.Column('min_value', sa.Integer(), nullable=True))
    op.drop_column('ranges', 'min')
    op.drop_column('ranges', 'max')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ranges', sa.Column('max', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('ranges', sa.Column('min', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('ranges', 'min_value')
    op.drop_column('ranges', 'max_value')
    # ### end Alembic commands ###
