"""empty message

Revision ID: 8b856cffcf8a
Revises: 874e3ee1d47c
Create Date: 2020-02-22 10:09:20.332291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b856cffcf8a'
down_revision = '874e3ee1d47c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('_is_active', sa.Boolean(), nullable=True))
    op.alter_column('users', 'google_token',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'google_token',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('users', '_is_active')
    # ### end Alembic commands ###
