"""empty message

Revision ID: 93adfcb064c4
Revises: 27b26ea9d40e
Create Date: 2020-02-21 15:26:09.932250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93adfcb064c4'
down_revision = '27b26ea9d40e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_username_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    # ### end Alembic commands ###
