"""empty message

Revision ID: a348563f6f71
Revises: 27b26ea9d40e
Create Date: 2020-02-21 15:58:53.551979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a348563f6f71'
down_revision = '27b26ea9d40e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings_strict')
    op.add_column('fields', sa.Column('is_strict', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fields', 'is_strict')
    op.create_table('settings_strict',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('is_strict', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('field_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], name='settings_strict_field_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='settings_strict_pkey'),
    sa.UniqueConstraint('field_id', name='unique_field')
    )
    # ### end Alembic commands ###
